CREATE TABLE [dbo].[ProductOffer] (
    [ProductOfferId]       INT               IDENTITY (1, 1) NOT NULL,
    [LU_OrderTypeId]       TINYINT           NOT NULL,
    [LU_CurrencyId]        TINYINT           NOT NULL,
    [ProductId]            INT               NOT NULL,
    [KittingNumber]        VARCHAR (12)      NULL,
    [OfferPrice]           DECIMAL(18,2)     NOT NULL,
    [IsVisibleInUI]        BIT               CONSTRAINT [DF_ProductOffer_IsVisibleInUI] DEFAULT 0 NOT NULL,
    [StartDateTime]        DATETIME2 (7)     NOT NULL,
    [EndDateTime]          DATETIME2 (7)     NULL,
    [LU_CultureId]         SMALLINT          NULL,
    [LU_CountryId]         TINYINT           NULL,
    [LU_WarehouseId]       TINYINT           NULL,
    [IsArchived]           BIT               CONSTRAINT [DF_ProductOffer_IsArchived] DEFAULT 0 NOT NULL,
    [IsSearchable]         BIT               CONSTRAINT [DF_ProductOffer_IsSearchable] DEFAULT 0 NOT NULL,
    [CreatedDateTime]      DATETIME2 (7)     CONSTRAINT [DF_ProductOffer_CreatedDateTime] DEFAULT (sysdatetime()),
    [UpdatedDateTime]      DATETIME2 (7)     NULL,
    CONSTRAINT [PK_ProductOffer] PRIMARY KEY CLUSTERED ([ProductOfferId] ASC),
    CONSTRAINT [FK_ProductOffer_LU_Country] FOREIGN KEY ([LU_CountryId]) REFERENCES [dbo].[LU_Country] ([LU_CountryId]),
    CONSTRAINT [FK_ProductOffer_LU_Culture] FOREIGN KEY ([LU_CultureId]) REFERENCES [dbo].[LU_Culture] ([LU_CultureId]),
    CONSTRAINT [FK_ProductOffer_LU_Currency] FOREIGN KEY ([LU_CurrencyId]) REFERENCES [dbo].[LU_Currency] ([LU_CurrencyId]),
    CONSTRAINT [FK_ProductOffer_LU_Warehouse] FOREIGN KEY ([LU_WarehouseId]) REFERENCES [dbo].[LU_Warehouse] ([LU_WarehouseId]),
    CONSTRAINT [FK_ProductOffer_LU_OrderType] FOREIGN KEY ([LU_OrderTypeId]) REFERENCES [dbo].[LU_OrderType] ([LU_OrderTypeId]),
    CONSTRAINT [FK_ProductOffer_Product] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Product] ([ProductId])
    );